FROM ansible/ansible:ubuntu1604

# install ansible
RUN apt-get update  && \
    apt-get install -y software-properties-common  && \
    apt-add-repository ppa:ansible/ansible  && \
    apt-get update  && \
    echo Y | apt-get install -y ansible

RUN apt-get install -y sshpass openssh-client

RUN pip install --upgrade pip

RUN pip install ansible[azure] \
    boto \
    apache-libcloud \
    pyrax \
    cs \
	azure-cli

# clean
RUN apt-get clean

#CMD ["ansible", "--version"]

COPY ansiblerunner.sh /ansible/ansiblerunner
RUN chmod +x /ansible/ansiblerunner
ENV PATH="/ansible:${PATH}"

ENTRYPOINT [ "ansiblerunner" ]