FROM ansible/ansible:ubuntu1604

# install ansible
RUN apt-get update  && \
    apt-get install -y software-properties-common  && \
    apt-add-repository ppa:ansible/ansible  && \
    apt-get update  && \
	apt-get install -y wget  && \
	apt-get install -y jq  && \
	apt-get install apt-transport-https lsb-release dirmngr -y  && \
    echo Y | apt-get install -y ansible

RUN apt-get install -y sshpass openssh-client

RUN pip install --upgrade pip
	 
RUN pip install ansible[azure] \
    boto \
    apache-libcloud \
    pyrax \
    cs

RUN AZ_REPO=$(lsb_release -cs)

RUN echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ wheezy main" | \
    tee /etc/apt/sources.list.d/azure-cli.list

RUN apt-key --keyring /etc/apt/trusted.gpg.d/Microsoft.gpg adv \
     --keyserver packages.microsoft.com \
     --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF
	 
RUN apt-get update

RUN apt-get install azure-cli

# clean
RUN apt-get clean

#CMD ["ansible", "--version"]

COPY ansiblerunner.sh /ansible/ansiblerunner
RUN chmod +x /ansible/ansiblerunner
ENV PATH="/ansible:${PATH}"

ENTRYPOINT [ "ansiblerunner" ]