FROM alpine

RUN apk update && \
    apk add bash jq py-pip && \
    apk add --virtual=build gcc libffi-dev musl-dev openssl-dev python-dev make && \
    apk add ansible && \
    pip install --upgrade pip && \
    pip install azure-cli && \
    pip install ansible[azure] && \
    apk del --purge build
	
COPY ansiblerunner.sh /ansible/ansiblerunner
RUN chmod +x /ansible/ansiblerunner
ENV PATH="/ansible:${PATH}"

ENTRYPOINT [ "ansiblerunner" ]