name: Add needs-triage label to new issue

on:
  issues:
    types: [opened]

jobs:
  needs-triage:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
