name: Add needs-triage label to new issue

on:
  issues:
    types: [opened]

jobs:
  needs-triage:
    runs-on: ubuntu-latest

    steps:
      - name: add labels
        uses: actions/labeler@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}